audit:
  id: testing-quality-assurance.test-data-management.production-data-masking
  name: Production Data Masking
  version: 1.0.0
  last_updated: '2026-01-22'
  status: active
  category: testing-quality-assurance
  category_number: 26
  subcategory: test-data-management
  tier: expert
  estimated_duration: 45-60 min
  completeness: complete
  requires_runtime: false
  destructive: false
execution:
  automatable: partial
  severity: critical
  scope: security
  default_profiles:
  - full
  - security
  - compliance
  blocks_phase: true
  parallelizable: true
description:
  what: |
    Evaluates data masking procedures applied when production data is
    used to populate test environments. Assesses masking techniques,
    coverage, consistency, and verification of de-identification.
  why_it_matters: |
    When production data is used for testing, improper masking exposes
    real user information. Masked data must be irreversibly anonymized
    while preserving data utility for testing. Inadequate masking leads
    to compliance violations and breach risks.
  when_to_run:
  - Before production data copy to test
  - Compliance audit preparation
  - Security assessment
  - Data handling policy review
prerequisites:
  required_artifacts:
  - type: masking_scripts
    description: Data masking automation
  - type: data_catalog
    description: Sensitive field documentation
  access_requirements:
  - Masking script access
  - Test database access
discovery:
  file_patterns:
  - glob: '**/scripts/mask*'
    purpose: Masking scripts
  - glob: '**/scripts/anonymize*'
    purpose: Anonymization scripts
  - glob: '**/data-catalog*'
    purpose: Data catalog
  code_patterns:
  - pattern: mask|anonymize|obfuscate|hash
    type: regex
    scope: scripts
    purpose: Masking operations
knowledge_sources:
  specifications:
  - id: gdpr-anonymization
    name: GDPR Anonymization Techniques
    url: https://gdpr-info.eu/recitals/no-26/
    offline_cache: true
    priority: required
  guides:
  - id: masking-guide
    name: Data Masking Best Practices
    url: https://www.delphix.com/glossary/data-masking
    offline_cache: true
  - id: anonymization-techniques
    name: Anonymization Techniques
    url: https://www.enisa.europa.eu/publications/data-pseudonymisation-technical-implementation-techniques
    offline_cache: true
  learning_resources:
  - id: data-protection
    title: Data Protection in Testing
    type: guide
    reference: Privacy Engineering Best Practices
tooling:
  static_analysis:
  - tool: Custom masking analyzer
    purpose: Masking coverage verification
    offline_capable: true
  infrastructure_tools:
  - tool: Delphix
    purpose: Enterprise data masking
    offline_capable: false
  - tool: DataVeil
    purpose: Data masking tool
    offline_capable: true
  scripts:
  - id: masking-check
    language: bash
    purpose: Verify masking coverage
    source: inline
    code: |
      #!/bin/bash
      echo "=== Production Data Masking Analysis ==="

      echo "Masking scripts:"
      find . -name '*mask*' -o -name '*anonymize*' -o -name '*obfuscate*' 2>/dev/null | head -10

      echo ""
      echo "Masking patterns in code:"
      grep -r -n 'mask\|anonymize\|obfuscate' --include='*.sql' --include='*.py' --include='*.js' . 2>/dev/null | head -15

      echo ""
      echo "Hash/encryption functions:"
      grep -r -E 'SHA256|MD5|bcrypt|hash\(' --include='*.sql' --include='*.py' . 2>/dev/null | head -10

      echo ""
      echo "Field mapping documentation:"
      find . -name '*data*catalog*' -o -name '*sensitive*fields*' -o -name '*pii*map*' 2>/dev/null
signals:
  critical:
  - id: MASK-CRIT-001
    signal: Production data copied without masking
    evidence_pattern: Direct production to test data copy
    explanation: |
      Unmasked production data in test environments exposes real user
      information. This violates privacy regulations and creates breach
      risk. All sensitive data must be masked before test use.
    remediation: |
      Implement mandatory masking:
      1. Block direct production data copies
      2. Create masking pipeline
      3. Apply masking at extraction
      4. Verify masking before load
      5. Audit masking completeness
  - id: MASK-CRIT-002
    signal: Reversible masking technique used
    evidence_pattern: Encryption without key destruction
    explanation: |
      Masking must be irreversible for proper anonymization. If the
      original data can be recovered, it's not true anonymization.
      Encryption keys must be destroyed or never accessible.
    remediation: |
      Use irreversible masking:
      - Hash sensitive values (one-way)
      - Replace with synthetic data
      - Destroy transformation keys
      - Use deterministic pseudonymization only when necessary
      - Document and justify any reversible techniques
  high:
  - id: MASK-HIGH-001
    signal: Incomplete field coverage
    evidence_pattern: Some sensitive fields not masked
    explanation: |
      Partial masking leaves PII exposed. All sensitive fields must be
      identified and masked. Missing even one field creates compliance
      risk and potential exposure.
    remediation: |
      Ensure complete coverage:
      - Catalog all sensitive fields
      - Map fields to masking rules
      - Verify all fields masked
      - Add new fields to catalog
      - Regular coverage audits
  - id: MASK-HIGH-002
    signal: Masking not consistently applied
    evidence_pattern: Same data masked differently across systems
    explanation: |
      Inconsistent masking can enable re-identification by correlating
      data across systems. The same value should mask to the same
      output to prevent correlation attacks.
    remediation: |
      Implement consistent masking:
      - Use deterministic techniques
      - Centralize masking logic
      - Apply same rules across systems
      - Test consistency across data sets
  medium:
  - id: MASK-MED-001
    signal: Masking not automated
    evidence_pattern: Manual masking steps
    remediation: Automate masking in data pipeline
  - id: MASK-MED-002
    signal: No masking verification
    evidence_pattern: Masked data not validated
    remediation: Add automated verification of masking completeness
  low:
  - id: MASK-LOW-001
    signal: Masking documentation outdated
    evidence_pattern: Field catalog not current
  positive:
  - id: MASK-POS-001
    signal: Automated masking pipeline
    evidence_pattern: All production copies automatically masked
  - id: MASK-POS-002
    signal: Masking verification in CI
    evidence_pattern: Automated PII scans after masking
procedure:
  context:
    cognitive_mode: critical
    ensemble_role: auditor
  steps:
  - id: '1'
    name: Identify masking automation
    description: |
      Find masking scripts and tools.
    duration_estimate: 10 min
    commands:
    - purpose: Find masking scripts
      command: find . -name '*mask*' -o -name '*anonymize*' 2>/dev/null | head -10
    - purpose: Check for masking tools
      command: grep -r 'masking\|anonymization' --include='*.yml' . 2>/dev/null | head -5
    expected_findings:
    - Masking automation
    - Tool usage
  - id: '2'
    name: Review field coverage
    description: |
      Assess which fields are masked.
    duration_estimate: 15 min
    commands:
    - purpose: Find field documentation
      command: find . -name '*catalog*' -o -name '*sensitive*' 2>/dev/null | head -5
    expected_findings:
    - Field coverage
    - Documentation status
  - id: '3'
    name: Verify masking techniques
    description: |
      Review masking methods used.
    duration_estimate: 15 min
    commands:
    - purpose: Check masking methods
      command: grep -r -E 'hash|SHA|replace|random' --include='*.sql' --include='*.py' . 2>/dev/null |
        head -10
    expected_findings:
    - Techniques used
    - Reversibility status
  - id: '4'
    name: Validate masked data
    description: |
      Confirm masking effectiveness.
    duration_estimate: 10 min
    questions:
    - Is masked data verified after transformation?
    - Can original values be recovered?
    - Is masking consistent across copies?
    expected_findings:
    - Verification status
    - Consistency assessment
output:
  deliverables:
  - type: finding_list
    format: structured
  - type: masking_report
    format: table
    sections:
    - Masking Coverage
    - Techniques Used
    - Verification Status
  - type: summary
    format: prose
    sections:
    - Executive Summary
    - Masking Assessment
    - Remediation Actions
  confidence_guidance:
    high: Full masking review with data verification
    medium: Script and documentation analysis
    low: Interview-based assessment
offline:
  capability: partial
  cache_manifest:
    knowledge:
    - source_id: masking-guide
      priority: required
profiles:
  membership:
    quick:
      included: false
      reason: Requires thorough security analysis
    security:
      included: true
      priority: 1
    compliance:
      included: true
      priority: 1
    full:
      included: true
      priority: 3
closeout_checklist:
- id: mask-001
  item: Masking automation identified
  level: CRITICAL
  verification: find . -name '*mask*' -o -name '*anonymize*' 2>/dev/null | wc -l
  expected: Count > 0 if production data used
- id: mask-002
  item: Field coverage verified
  level: CRITICAL
  verification: manual
  verification_notes: Confirm all sensitive fields are masked
  expected: 100% coverage
- id: mask-003
  item: Irreversibility confirmed
  level: BLOCKING
  verification: manual
  verification_notes: Verify masking cannot be reversed
  expected: Irreversible techniques used
governance:
  applicable_to:
    archetypes:
    - all
  compliance_frameworks:
  - framework: GDPR
    controls:
    - Art. 5
    - Art. 25
    - Art. 32
  - framework: CCPA
    controls:
    - '1798.100'
    - '1798.140'
  - framework: HIPAA
    controls:
    - '164.514'
  - framework: PCI-DSS
    controls:
    - '3.4'
relationships:
  commonly_combined:
  - testing-quality-assurance.test-data-management.test-data-privacy
  - testing-quality-assurance.test-data-management.test-data-strategy
  - security-trust.data-protection.data-classification
