audit:
  id: operational-excellence.production-readiness.production-checklist
  name: Production Checklist Audit
  version: 1.0.0
  last_updated: '2025-01-22'
  status: active
  category: operational-excellence
  category_number: 25
  subcategory: production-readiness
  tier: expert
  estimated_duration: 2-3 hours  # median: 2h
  completeness: complete
  requires_runtime: false
  destructive: false
execution:
  automatable: partial
  severity: critical
  scope: process
  default_profiles:
  - full
  - production
  - launch
description:
  what: |
    This audit examines production readiness checklists including:
    - Checklist existence and comprehensiveness
    - Coverage of operational requirements
    - Monitoring and alerting requirements
    - Security and compliance requirements
    - Documentation requirements
    - Rollback and recovery requirements
    - Capacity and scaling requirements
    - On-call and support requirements
  why_it_matters: |
    Production checklists prevent launch failures:
    - Systematic verification of readiness
    - Consistent launch quality
    - Reduced operational surprises
    - Knowledge capture of requirements

    Google's Production Readiness Review process ensures new
    services meet operational standards before serving users,
    preventing many categories of incidents.
  when_to_run:
  - Before service launches
  - Before major releases
  - When updating launch processes
  - During operational reviews
  - After launch incidents
prerequisites:
  required_access:
  - Production checklists
  - Launch process documentation
  - Historical launch records
  - Incident post-mortems
  required_knowledge:
  - Operational requirements
  - Monitoring standards
  - Security requirements
  - Compliance obligations
discovery:
  documentation_review:
  - Review production checklists
  - Examine launch process documentation
  - Check checklist completion records
  - Analyze post-launch incidents
  process_analysis:
  - Interview launch participants
  - Review checklist enforcement
  - Check exception handling
  - Analyze checklist evolution
  file_patterns:
  - glob: '**/runbook*.md'
    purpose: Runbook documentation
  - glob: '**/playbook*.md'
    purpose: Playbook documentation
  - glob: '**/sop*.md'
    purpose: Standard operating procedures
  - glob: '**/oncall*.yaml'
    purpose: On-call configuration
  code_patterns:
  - pattern: runbook|playbook|incident|escalation|sla
    type: regex
    scope: all
    purpose: Operations references
knowledge_sources:
  authoritative:
  - Google SRE - Production Readiness
  - Site Reliability Workbook
  - Release It! by Michael Nygard
  - DevOps Handbook
  supplementary:
  - Launch checklists from tech companies
  - Industry launch standards
tooling:
  assessment:
  - name: Checklist Management Tools
    purpose: Track checklist completion
  - name: Launch Tracking Systems
    purpose: Monitor launch process
  automation:
  - name: Automated Verification
    purpose: Validate checklist items
  - name: Launch Gate Systems
    purpose: Enforce checklist completion
signals:
  critical:
  - id: PC-CRIT-001
    signal: No production readiness checklist exists
    evidence_indicators:
    - Services launched without systematic review
    - No documented launch requirements
    - Ad-hoc launch processes
    remediation: |
      - Create comprehensive checklist
      - Define required vs optional items
      - Establish enforcement process
      - Train teams on requirements
      - Track checklist completion
  - id: PC-CRIT-002
    signal: Checklist routinely bypassed
    evidence_indicators:
    - Launches occur without checklist
    - Exceptions are the norm
    - No enforcement mechanism
    remediation: |
      - Implement enforcement gates
      - Require documented exceptions
      - Executive approval for bypasses
      - Track bypass frequency
      - Investigate root causes
  high:
  - id: PC-HIGH-001
    signal: Checklist missing critical categories
    evidence_indicators:
    - No monitoring requirements
    - Security not covered
    - No operational readiness items
    remediation: |
      - Audit checklist completeness
      - Add missing categories
      - Include all stakeholders
      - Benchmark against industry
      - Update based on incidents
  - id: PC-HIGH-002
    signal: Checklist items not verifiable
    evidence_indicators:
    - Subjective checklist items
    - Cannot verify completion
    - Self-attestation only
    remediation: |
      - Make items objective
      - Add verification methods
      - Implement automated checks
      - Require evidence for items
      - Review completion quality
  medium:
  - id: PC-MED-001
    signal: Checklist not updated from incidents
    evidence_indicators:
    - Incidents reveal missing items
    - Same issues recur
    - No learning integration
    remediation: |
      - Review incident history
      - Update checklist from learnings
      - Establish feedback loop
      - Regular checklist reviews
      - Version control checklist
  - id: PC-MED-002
    signal: Different teams use different checklists
    evidence_indicators:
    - Inconsistent launch quality
    - No standard checklist
    - Teams create own checklists
    remediation: |
      - Standardize base checklist
      - Allow team-specific additions
      - Central checklist management
      - Share best practices
      - Regular alignment reviews
  low:
  - id: PC-LOW-001
    signal: Checklist completion not tracked
    evidence_indicators:
    - No historical records
    - Cannot audit past launches
    - Completion rates unknown
    remediation: |
      - Track all checklist completions
      - Store historical records
      - Report completion metrics
      - Analyze completion trends
      - Identify problem areas
  positive:
  - id: PC-POS-001
    signal: Comprehensive, enforced production checklist
    evidence_indicators:
    - All launches use checklist
    - Items verifiable and verified
    - Checklist evolves from learnings
    - High completion rates
    validation: Review checklist and completion records
procedure:
  step_1:
    name: Review checklist existence
    actions:
    - Locate production checklists
    - Identify all checklist variants
    - Check checklist ownership
    - Review update history
  step_2:
    name: Analyze checklist content
    actions:
    - Review all checklist items
    - Check category coverage
    - Verify item clarity
    - Assess verification methods
  step_3:
    name: Evaluate enforcement
    actions:
    - Check enforcement mechanisms
    - Review exception process
    - Analyze bypass frequency
    - Interview stakeholders
  step_4:
    name: Assess effectiveness
    actions:
    - Review post-launch incidents
    - Check completion rates
    - Analyze improvement trends
    - Compare with best practices
output:
  artifacts:
  - Checklist assessment report
  - Coverage gap analysis
  - Enforcement effectiveness review
  - Improvement recommendations
  metrics:
  - Checklist category coverage
  - Completion rate percentage
  - Exception frequency
  - Post-launch incident rate
closeout_checklist:
- id: pc-001
  item: Production checklist exists
  level: CRITICAL
  verification: manual
  verification_notes: Verify comprehensive checklist documented
  expected: Confirmed by reviewer
- id: pc-002
  item: Checklist enforcement in place
  level: BLOCKING
  verification: manual
  verification_notes: Verify enforcement mechanisms exist
  expected: Confirmed by reviewer
- id: pc-003
  item: Checklist covers all categories
  level: REQUIRED
  verification: manual
  verification_notes: Verify monitoring, security, ops coverage
  expected: Complete category coverage
governance:
  applicable_to:
    archetypes:
    - all
  compliance_frameworks:
  - framework: Google SRE
    controls:
    - Production Readiness Review
relationships:
  commonly_combined:
  - operational-excellence.production-readiness.readiness-review
  - operational-excellence.production-readiness.monitoring-readiness
